name: Build Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Run pyinstaller
        run: uv run pyinstaller -F main.py --hidden-import numpy.core.multiarray

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: tapolightsync-${{ matrix.os }}
          path: dist/*
