name: Build Binaries

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux
            arch: x86_64

          - os: ubuntu-24.04-arm
            platform: linux
            arch: arm64

          - os: windows-latest
            platform: windows
            arch: x86_64

          - os: macos-15-intel
            platform: macos
            arch: x86_64

          - os: macos-latest
            platform: macos
            arch: arm64
    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v6

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Set up Python
        run: uv python install

      - name: Install the project
        run: uv sync --locked --all-extras --dev

      - name: Build binary (Linux x86_64)
        if: ${{matrix.platform == 'linux' && matrix.arch == 'x86_64'}}
        run: uv run pyinstaller --name tapolightsync -F main.py --add-binary '.venv/lib/python3.12/site-packages/tls_client/dependencies/tls-client-x86.so:tls_client/dependencies' --add-binary '.venv/lib/python3.12/site-packages/tls_client/dependencies/tls-client-amd64.so:tls_client/dependencies'

      - name: Build binary (Linux arm64)
        if: ${{matrix.platform == 'linux' && matrix.arch == 'arm64'}}
        run: uv run pyinstaller --name tapolightsync -F main.py --add-binary '.venv/lib/python3.12/site-packages/tls_client/dependencies/tls-client-arm64.so:tls_client/dependencies'

      - name: Build binary (Windows x86_64)
        if: ${{matrix.platform == 'windows' && matrix.arch == 'x86_64'}}
        run: uv run pyinstaller --name tapolightsync -F main.py --add-binary '.venv/Lib/site-packages/tls_client/dependencies/tls-client-64.dll;tls_client/dependencies'

      - name: Build binary (Macos x86_64)
        if: ${{matrix.platform == 'macos' && matrix.arch == 'x86_64'}}
        run: uv run pyinstaller --name tapolightsync -F main.py --add-binary '.venv/lib/python3.12/site-packages/tls_client/dependencies/tls-client-x86.dylib:tls_client/dependencies'

      - name: Build binary (Macos arm64)
        if: ${{matrix.platform == 'macos' && matrix.arch == 'arm64'}}
        run: uv run pyinstaller --name tapolightsync -F main.py --add-binary '.venv/lib/python3.12/site-packages/tls_client/dependencies/tls-client-arm64.dylib:tls_client/dependencies'

      - name: Upload artifact
        uses: actions/upload-artifact@v6
        with:
          name: tapolightsync-${{ matrix.platform }}-${{ matrix.arch }}
          path: dist/*
